[package]
name = "puniyu"
version = "0.1.0"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
log = { workspace = true }

[lints]
workspace = true

[[bin]]
name = "punicore"
path = "src/main.rs"