[package]
name = "puniyu_utils"
version = "0.1.0"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
rust_decimal = { version = "1.37.2" }
puniyu_system_info = { version = "0.5.0" }
log = { workspace = true }
tokio = { workspace = true }
redis = { version = "0.32.5", features = ["tokio-comp"] }
toml = { version = "0.9.5" }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { version = "0.9.34" }
regex = "1.11.1"
deadpool-redis = { version = "0.22.0", features = ["rt_tokio_1"] }

[lints]
workspace = true
