[package]
name = "puniyu_core"
version = "0.1.0"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
puniyu_logger = { path = "../puniyu_logger" }
puniyu_system_info = { version = "0.4" }
tracing = { version = "0.1.41" }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }

[lints]
workspace = true
