[package]
name = "puniyu_core"
version = "0.1.0"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tracing = { version = "0.1.41" }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
tokio = "1.47.1"
emitter-rs = { version = "0.0.5" }
lazy_static = { workspace = true }

puniyu_logger = { path = "../puniyu_logger" }
puniyu_utils = { path = "../puniyu_utils" }
puniyu_plugin = { path = "../puniyu_plugin" }

[lints]
workspace = true
