[package]
name = "puniyu_core"
version = "0.1.0"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
puniyu_logger = { path = "../puniyu_logger" }
tracing = { version = "0.1.41" }

[lints]
workspace = true
