name: release
on:
  push:
    branches:
      - main
    paths:
      - 'Cargo.toml'
      - 'puniyu/*'
      - 'puniyu_core/*'
      - 'puniyu_logger/*'
      - 'puniyu_utils/**'
      - '../../puniyu_registry/*'
  pull_request_target:
    paths:
      - 'Cargo.toml'
      - 'puniyu/*'
      - 'puniyu_core/*'
      - 'puniyu_logger/*'
      - 'puniyu_utils/**'
      - '../../puniyu_registry/*'
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      logger: ${{ steps.release.outputs['puniyu_logger--release_created'] }}
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 运行 release-please-action
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
